apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-db-deploy
  labels:
    app: video-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-db
  template:
    metadata:
      labels:
        app: video-db
    spec:
      containers:
      - name: video-db
        image: echuchu/video_db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: video-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: video-db-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: video-db-service
spec:
  selector:
    app: video-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  # type: ClusterIP