version: "3.9"
services:
  mysql:
    build: 
      context: ./video_db
      dockerfile: Dockerfile
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=video_user
      - MYSQL_DATABASE=video_database
      - MYSQL_PASSWORD=video_password
    volumes:
      - mysql:/var/lib/mysql

  python:
    build:
     context: ./web_upload
     dockerfile: ./web_upload/Dockerfile
    restart: always
    container_name: "upload_videos"
    image: python:latest
    ports:
      - 5000:5000 ## >:D
    links:
      - mysql
    network_mode: bridged

  authentication:
    build:
      context: ./auth
      dockerfile: ./auth/Dockerfile
    restart: always
    container_name: "auth_server"
    image: nginx:latest
    ports:
      - 8080:80
      - 30532:30532
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - SERVER_NAME=proxy.acit3495.net
      - PORT=80

volumes:
  mysql:

# :D



  