version: "3.9"
services:
  mysql:
    build: 
      context: ./video_db
      dockerfile: Dockerfile
    # restart: always
    container_name: "mysql"
    # image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=video_user
      - MYSQL_DATABASE=video
      - MYSQL_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      upload_network:
        aliases:
          - mysql
      streaming_network:
        aliases:
          - mysql

  upload_server:
    build:
     context: ./web_upload
     dockerfile: Dockerfile
    # restart: always
    container_name: "upload_videos"
    # image: python:latest
    ports:
      - 5000:5000
    links:
      - mysql
    networks:
      upload_network:
        aliases:
          - upload
      web_network:
        aliases:
          - upload

  stream_server:
    build:
     context: ./web_streaming
     dockerfile: Dockerfile
    # restart: always
    container_name: "stream_videos"
    # image: python:latest
    ports:
      - 5001:5000
    links:
      - mysql
    networks:
      streaming_network:
        aliases:
          - stream
        # ipv4_address: 172.27.0.4
      web_network:
        aliases:
          - stream

  authentication_server:
    build:
      context: ./auth
      dockerfile: Dockerfile
    # restart: always
    container_name: "auth_server"
    # image: nginx
    ports:
      - 8080:80
      - 30532:30532
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - SERVER_NAME=proxy.acit3495.net
      - PORT=80
    networks:
      web_network:
        aliases:
          - auth
      bridge:
        aliases:
          - auth

  filesys:
    build:
      context: ./filesys
      dockerfile: Dockerfile
    # restart: always
    container_name: "filesys"
    # image: ubuntu
    ports:
      - 50000:20
    volumes:
      - videos:/srv/ftp
    networks:
      streaming_network:
        aliases:
          - filesys
      upload_network:
        aliases:
          - filesys

volumes:
  mysql:
  videos:


networks:
  upload_network:     # Connects Upload, File Sys, and DB
    driver: bridge
    internal: true
  streaming_network:  # Connects Stream, File Sys, and DB
    driver: bridge
    internal: true
  web_network:        # Connects Auth, Upload, and Stream
    driver: bridge
    internal: true
  bridge:             # Connects Auth to the internet
    driver: bridge


  